swagger: '2.0'
info:
  description: Auth in nodejs
  version: 1.0.0
  title: Microservice for authentication
  license:
    name: Software Architecture, 2019-II

host: localhost:3000
basepath: /

paths:
  /signin:
    post:
      summary: Sign in
      description: singin authentication
      consumes:
        - application/x-www-form-urlencoded
      parameters:
      - in: formData
        name: email 
        description: pass a valid email
        required: true
        type: string
      - in: formData
        name: password
        description: pass a password
        type: string
        required: true
        minimum: 0
      responses:
        200:
          description: Ok
  /signup:
    post:
      summary: Sign up
      description: signup authentication
      consumes:
        - application/x-www-form-urlencoded
      parameters:
      - in: formData
        name: email 
        description: pass a valid email
        required: true
        type: string
      - in: formData
        name: password
        description: pass a password
        type: string
        required: true
        minimum: 0
      responses:
        200:
          description: Ok
    
definitions:
  Item:
    type: object
    required:
    - email
    - password
    properties:
      email:
        type: string
        example: user@unal.edu.co
      password:
        type: string
        example: 1234



