swagger: '2.0'
info:
  description: Auth in nodejs
  version: 1.0.0
  title: Microservice for authentication
  license:
    name: Software Architecture, 2019-II
host: localhost:3000
basePath: /
paths:
  /signup/{name}&{password}:
    post:
      summary: Sign up
      description: singin authentication
      parameters:
      - in: path
        name: name
        description: username
        required: true
        type: string
      - in: path
        name: password
        description: user password
        type: string
        required: true
      responses:
        200:
          description: user created
  /api/signin/{name}&{password}:
    get:
      - in: path
        name: name
        description: username
        required: true
        type: string
      - in: path
        name: password
        description: user password
        type: string
        required: true
      responses:
        200:
          description: token user
        401:
          description: Unauthorized, user or password incorrect
        

