version: '3'
services:
  web:
    build: .
    command: node server.js
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"

  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
  

